import type { Metadata } from "next";
import { fira_code } from "./fonts";
import { Header } from "@/components/header";

import "../styles/globals.css";

export const metadata: Metadata = {
  title: "My portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="container my-10 ">
      <body className={fira_code.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
